name: Day 44 Task-4 | Download Artifacts Between Jobs

on:
    workflow_dispatch:
        
jobs:
    upload-artifacts:
        runs-on: ubuntu-latest
        steps:
            - name: Create a simple text file
              run: |
                mkdir -p log-directory
                echo "This is simple text file" >> log-directory/sample.txt

            - name: Create a log file
              run: |
                cat >> log-directory/log.txt << EOF
                INFO: This is log file for test
                INFO: Branch name - ${{github.ref_name}}
                INFO: Triggered by - ${{github.actor}}
                INFO: Commit SHA - ${{github.sha}}
                INFO: Workflow - ${{github.workflow}}
                INFO: Job status - SUCCESS
                EOF
              
            - name: upload artifects
              uses: actions/upload-artifact@v4
              with:
                name: my-log-file
                path: log-directory/log.txt
    
    download-artifacts:
      runs-on: ubuntu-latest
      needs: upload-artifacts
      steps:
        - name: download artifects
          uses: actions/download-artifact@v5
          with:
            name: my-log-file
            path: downloaded-content
       
        - name: List Directory Structure
          run: ls -R downloaded-content

        - name: Print File content
          run: cat downloaded-content/log.txt
        