name: Day 43 Task-2 | Environment Variables

on:
    workflow_dispatch:

#Workflow level env varibale
env:
    APP_NAME: myapp

jobs:
    environment_variable:
        runs-on: ubutnu-latest
        env:
            ENVIRONMENT: stagging
        steps:
            - name: Printing all environment variable info
              env:
                VERSION: 1.0.0
              run: |
               echo "Workflow level env: $APP_NAME"
               echo "Job level env: $ENVIRONMENT"
               echo "Step level env: $VERSION"
               echo "Commit SHA: ${{github.sha}}"
               echo "Github Actor: ${{github.actor}}"

