name: Day 43 Task-4 | Conditionals

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:
  
jobs:
  main_branch:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: run when push on main branch
        if: github.ref == 'refs/heads/main'
        run: |
         echo "Run's when anything done on main branch"
  
  previous_step_failed:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Failed step
        run: echo "Failing this step to test run on failed step."
          exit 1

      - name: Run on Previous Step Failed
        run: echo "Steps executed because previous step got failed."


  on_push_only:
    if: github.event_name != 'pull_request'
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Run only on push events not on pull request
        run: echo "on push events"

      - name: Failed step, Continue on error
        run: echo "Failing step"
          exit 1
        continue-on-error: true