name: Day 43 Task-3 | Job Outputs

on:
  workflow_dispatch:

jobs:
  set_date:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    outputs:
      todayDate: ${{ steps.set-date.outputs.date }}
    steps:
      - name: Setting today's date
        id: set-date
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
  
  print_date:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: set_date
    steps:
      - name: Print the current date
        run: echo "Current Date:" ${{ needs.set_date.outputs.todayDate }}


