name: Day 44 Task-1 | Github Secrets

on:
    workflow_dispatch:

jobs:
    test-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Check if secret is set
              run: |
                if [ -n "${{secrets.MY_SECRET_MESSAGE}}" ]; then
                echo "Secret is set: TRUE"
                else
                echo "Secret is set: FALSE"
                fi

            - name: print secret
              run: echo "Secret is:" ${{secrets.MY_SECRET_MESSAGE}}
