name: Day-47 Task-1 | Pull Request Event Types

on:
  #  pull_request:
  #      types: 
  #        - opened
  #        - synchronize
  #        - reopened
  #        - closed
  workflow_dispatch:
    

jobs:
    pull-request-infomation:
        runs-on: ubuntu-latest
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        steps:
            - name: Print Fired Event Type
              run: echo "Event type:" ${{ github.event.action }}
        
            - name: Print Pull Request Title
              run: echo "Pull Request Title:" ${{github.event.pull_request.title}}

            - name: Print Pull request Author
              run: echo "Pull Request Author:" ${{github.event.pull_request.user.login}}

            - name: Print Source and Target Branch
              run: |
                echo "Source: " ${{github.head_ref}}
                echo "Target: " ${{github.base_ref}}
            
            - name: PR Merged step          # only runs when PR is merged
              run: |
                echo "PR was MERGED into ${{ github.base_ref }}"
                echo "Merged by : ${{ github.event.pull_request.merged_by.login }}"
                echo "Merged at : ${{ github.event.pull_request.merged_at }}"